### ISSUE TITLE
How to get observation_next

### ISSUE THREAD

**Issue by j0rd1smit** [takuseno/d4rl-atari#1]
How do I get the next observations? Can I assume that the dataset is ordered? If so the following should work, right?
```
observation = dataset['observations'][i]
observation_next = dataset['observations'][i + 1]
```

**Comment by takuseno** [comment]
@j0rd1smit Hello. Yes, the data is chronologically ordered.

**Comment by takuseno** [comment]
Let me close this issue since this seems to be resolved.
