### ISSUE TITLE
why using NoFrameskip environment?

### ISSUE THREAD

**Issue by GilgameshD** [takuseno/d4rl-atari#12]
In the document of the DQN Replay Dataset, it says:

"Note that the dataset consists of approximately 50 million tuples due to frame skipping (i.e., repeating a selected action for k consecutive frames) of 4"

but I notics that the online environment is built with *NoFrameskip*. Is there any reason for this?

**Comment by takuseno** [comment]
You do not need to worry about this. It's handled inside `AtariPreprocessing`.
https://github.com/takuseno/d4rl-atari/blob/799428bbc570a224c2df58a78c878f3410b0fa59/d4rl_atari/envs.py#L27

**Comment by GilgameshD** [comment]
cool, thanks for your answer.
