### ISSUE TITLE
subsample used? 200 m to 1 m frames

### ISSUE THREAD

**Issue by weiguowilliam** [takuseno/d4rl-atari#2]
Based on the Google's post, it use 200m frames. I wonder what kind of subsample methods are used to keep only 1m frames? Thank you.

**Comment by takuseno** [comment]
@weiguowilliam Hello, thank you for the issue! Google's dataset is consisting of 200M frames per seed on each game. The 200M frames of the data are divided into 20 chunks of 1M frames. So, in this library, one of the chunks is loaded to make up the dataset with 1M frames. Although mixing up frames in different epochs needs more memory space and time to process, we can add that feature.

**Comment by weiguowilliam** [comment]
Thank you! 1m frames should be enough:)
